### ISSUE TITLE
Theme not rendering on firebase and on debug mode 

### ISSUE THREAD

**Issue by PRedemption** [gethugothemes/bigspring-light#66]
Theme not  rendering well on Google Chrome in debug mode or when deployed on firebase. But on Netlify
![Screenshot from 2022-06-27 07-28-28](https://user-images.githubusercontent.com/82599930/175866110-ba16d6b4-da91-4fb5-898d-0ce80a4e7057.png)
 is working well.

**Comment by tfsomrat** [comment]
Hello @PRedemption 

I think you didn't fill the `baseURL` field with the exact URL,  in the `config/_default/config.toml` file.

**Comment by 0x111** [comment]
I had a similar issue, the problem for me was that I did not had the contents of this git repo in a folder named `bigspring-light`, so I had to change the line in the config.toml to the folder name where the files were. (root folder where you put the git repo contents)

https://github.com/gethugothemes/bigspring-light/blob/248923a6c7e0a6853b560412be81cffc36f0c373/exampleSite/config/_default/config.toml#L4

This fixed the problem
