### ISSUE TITLE
Hamburger no response and regex error

### ISSUE THREAD

**Issue by hcheng826** [gethugothemes/bigspring-light#67]
Hi community, I'm using the bigspring theme with a very simple config. Encountered 2 problems:

1. There are some Regex related error in the console
<img width="611" alt="image" src="https://github.com/gethugothemes/bigspring-light/assets/23033847/979bce2b-98ef-4c2d-a70d-723a8ba38bf6">

2. Not sure if related to the issue above. The hamburger (stack of 3 lines button) for expanding navbar on narrow screen (mobile) has no response. 

I tried to update the submodule using the latest master branch but still getting the issue. Does anyone got similar issue? Appreciate it!

For reference:
here's the website: https://www.ntuadf.org/
and this is the repo for: https://github.com/ntuadf/ntuadf.github.io/tree/master

**Comment by tfsomrat** [comment]
Hi @hcheng826 
I have checked the live demo https://demo.gethugothemes.com/bigspring-light/site/ and found no issues. you must have messed up something. we don't cover this type of support here. You can take our service to fix and improve your site [here](https://gethugothemes.com/get-a-quote) [Paid]
